# 2. Python para Cómputo Científico.
Introducción a la librería NumPy

* Es una librería fundamental para el cómputo numérico.
* Incluye potentes funciones de algebra lineal, numeros pseudo aleatorios, cómputo matricial etc...
* Es mas rápido que la librería estándar de Python para la manipulación y operaciones matriciales en álgebra lineal.
* Es utilizado para cómputo científico.
* Tiene herramientas para intergrr otros lenguajes como C, C++, Fortran 

Para importar la librería numpy hacemos.

In [5]:
import numpy as np

Una clase fundamental de Numpy es la clase ```array```

In [8]:
#crear un arreglo unidimensional a partir de una lista de python
L = range(5)

np.array(L)

array([0, 1, 2, 3, 4])

In [11]:
L = [[i for i in range(5)] for j in range(5)]

np.array(L)

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [22]:
L = [[[0 for i in range(5)] for j in range(4)] for k in range(3)]

print("verificando dimensiones:",np.array(L).shape)
print(np.array(L))

verificando dimensiones: (3, 4, 5)
[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


Numpy nos facilita la tarea de generar matrices

In [29]:
np.empty((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [30]:
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [31]:
np.full((3,4,5), 4)

array([[[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]],

       [[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]],

       [[4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4]]])

In [33]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [34]:
np.arange(4, 4000, 45)

array([   4,   49,   94,  139,  184,  229,  274,  319,  364,  409,  454,
        499,  544,  589,  634,  679,  724,  769,  814,  859,  904,  949,
        994, 1039, 1084, 1129, 1174, 1219, 1264, 1309, 1354, 1399, 1444,
       1489, 1534, 1579, 1624, 1669, 1714, 1759, 1804, 1849, 1894, 1939,
       1984, 2029, 2074, 2119, 2164, 2209, 2254, 2299, 2344, 2389, 2434,
       2479, 2524, 2569, 2614, 2659, 2704, 2749, 2794, 2839, 2884, 2929,
       2974, 3019, 3064, 3109, 3154, 3199, 3244, 3289, 3334, 3379, 3424,
       3469, 3514, 3559, 3604, 3649, 3694, 3739, 3784, 3829, 3874, 3919,
       3964])

In [36]:
#genera una secuencia de  5 valores equidistantes entre 0 y 100
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [37]:
np.random.random((4,5)) 

array([[0.47663965, 0.6456948 , 0.19145593, 0.40662655, 0.36239301],
       [0.63158637, 0.69907579, 0.52762395, 0.02665038, 0.88148493],
       [0.74454432, 0.67861862, 0.49927299, 0.97486529, 0.10354503],
       [0.76060831, 0.91910243, 0.38423546, 0.61003492, 0.42395698]])